#!/bin/sh



case "$1" in
    start)
        $JAVA $JAVA_OPTS $ILIAS_HOME/$JAR $CONFIG start
        ;;
    status)
        $JAVA $JAVA_OPTS $ILIAS_HOME/$JAR $CONFIG status
        ;;
    stop)
        $JAVA $JAVA_OPTS $ILIAS_HOME/$JAR $CONFIG stop
        ;;
    *)
        echo "No idea what you mean with '$1'"
        exit 1;
        ;;
esac
